services:
  bff-api:
    image: fakebook-bff:v7
    container_name: fakebook-bff-api
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: https://+:8080
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/fakebook-bff.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: fakebook-bff123
    ports:
      - "7000:8080"
    volumes:
      - ./../certs:/https:ro
    depends_on:
      auth-api:
        condition: service_healthy
      feed-api:
        condition: service_healthy
      redis:
        condition: service_started

  feed-api:
    image: fakebook-feed:v3
    container_name: fakebook-feed-api
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: http://+:8080
      MessageBroker__Host: rabbitmq
      MessageBroker__Username: fakebook
      MessageBroker__Password: fakebook
    ports:
      - "7002:8080"
    depends_on:
      feed-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  feed-db:
    image: postgres:17
    container_name: fakebook-feed-db
    environment:
      POSTGRES_DB: fakebook_feed
      POSTGRES_USER: fb_feed
      POSTGRES_PASSWORD: fb_feed_123
    ports:
      - "5434:5432"
    volumes:
      - feed_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fb_feed -d fakebook_feed"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-api:
    image: fakebook-auth:v4
    container_name: fakebook-auth-api
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: http://+:8080
      MessageBroker__Host: rabbitmq
      MessageBroker__Username: fakebook
      MessageBroker__Password: fakebook
    ports:
      - "7001:8080"
    depends_on:
      auth-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  auth-db:
    image: postgres:17
    container_name: fakebook-auth-db
    environment:
      POSTGRES_DB: fakebook_auth
      POSTGRES_USER: fb_user
      POSTGRES_PASSWORD: fb_user_123
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fb_user -d fakebook_auth"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: fakebook-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: fakebook
      RABBITMQ_DEFAULT_PASS: fakebook

  redis:
    image: redis:7-alpine
    container_name: fakebook-redis
    ports:
      - "6379:6379"

volumes:
  auth_db_data:
  feed_db_data:
