services:
  auth-api:
    image: fakebook-auth:v1
    container_name: fakebook-auth-api
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: https://+:8080
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/fakebook-auth.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: fakebook-auth123
    ports:
      - "6001:8080"
    volumes:
      - ./../certs:/https:ro
    depends_on:
      auth-db:
        condition: service_healthy

  auth-db:
    image: postgres:17
    container_name: fakebook-auth-db
    environment:
      POSTGRES_DB: fakebook_auth
      POSTGRES_USER: fb_user
      POSTGRES_PASSWORD: fb_user_123
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fb_user -d fakebook_auth"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  auth_db_data:
